### ISSUE TITLE
Allow for defining clone point 

### ISSUE THREAD

**Issue by Grokzen** [dynamist/subgit#33]
This is a rewrite of #2 with some updates

Right now we only have the ability to clone into the same folder. But we want to be able to clone into a sub-folder if possible.

Extend the configuration for a repo to allow for the option `clone-path: <folder-path>` for any repo we define

If this is set then we should attempt to clone the git repo into this folder. But there is two different cases here.

The first is that we might want to clone one git repo into the already cloned repo of another repo. So lets say we have the repo `pykwalify/` that we already have cloned to disk. We want to clone another repo `redis-py-cluster` into the folder path `pykwalify/redis-cluster/` instead of the root folder we stand in. The problem here is that we must have some kind of dependency resolution where we must say what order repos should be processed in to allow for this as we can't create a random folder, clone `redis-py-cluster` into it first, then clone and overwrite `pykwalify/` on the same folder. Add ontop of this that our configuration file is a nested dict that do not guarantee or preserv insert order always so we can't guarantee that we will always process pykwalify before redis-py-cluster for instance.

If we go down dependency order lane, keep it as simple as possible, depnedencies must be defined where one repo "depends on" another repo, the tool will just re-order the execution order to fullfill the dependencies, then execute the commands in that order.

The second alterantive we have is that we just ignore any dependencies and we hope that subgit just executes things in the correct order. This might cause issues and problems if we only let this to chanse. The upside is that this is way simpler to implement and we might just impelment the feature and add in dependency handling later on to move the tool forward.

**Comment by holmboe** [comment]
As it currently stands #63 expects a format like this:

```yaml
repos:
  - name: pyk
    url: git@github.com:Grokzen/pykwalify.git
    sparse:
      paths:
        - "docs"
        - "tests"
    revision:
      branch: master
  - name: pykwalify
    url: git@github.com:Grokzen/pykwalify.git
    sparse:
      paths:
        - "docs"
        - "tests"
    clone_point: "pyk/docs"
    revision:
      tag:
        filter: "[0-9].[0-9].[0-9]"
        order: semver  # This is also the default value if not specified
        select: last  # Defaults to semver style
```

However my personal preference would be to use the `name` to specify the clone point path instead of introducing a new `clone_point` key.

Like this:

```yaml
repos:
  - name: pyk
    url: git@github.com:Grokzen/pykwalify.git
    sparse:
      paths:
        - "docs"
        - "tests"
    revision:
      branch: master
  - name: "pyk/docs"
    url: git@github.com:Grokzen/pykwalify.git
    sparse:
      paths:
        - "docs"
        - "tests"
    revision:
      tag:
        filter: "[0-9].[0-9].[0-9]"
        order: semver  # This is also the default value if not specified
        select: last  # Defaults to semver style
```

**Comment by Grokzen** [comment]
Good suggestion and `clone_point` was renamed into `path` instead

But the merged `name+clone_point` and adding `alias` idea will not be implemented due to that name is used as the input argument from the cli for all actions done by this tool. If we force the user to write something like `subgit pull pyk/docs/` instead of just `subgit pull pyk` that really makes things complex. Second argument against this is that you mash up the easy to understand names of `name & path` with a more difficult to understand pair of `name + alias` where name don't mean name and alias is just a worse name for name.

These changes was added into PR #63

**Comment by rholmboe** [comment]
To keep on topic, I think that this implementation of `path` and `subgit pull <subcommand>` shouldn't be either this or that discussion, but both.

In best of worlds, `subgit pull [name|path]` should be implemented as a valid commands, both for simplify logic, bash completions or user friendliness.

---

But for the sake of argument, I'd like to drop the requirement of `name` key to have a minimalistic approach to only make key `url` into the mandatory field.

`name` in that sense should be derived from repository name (ie, `.../Grokzen/pykwalify.git` -> `pykwalify`), same as `path` would.

Example configuration:
```
repos:
  - url: https://github.com/username/repository.git
  - url: https://git.local/username/repo.git
```
This would result in cloning `repository.git` into `./repository` and `repo.git` into `./repo`

And with that change, I would love to see an `alias` key to be introduced as a replacement/deprecation for `name`, which should populate `path` variable if used, but `path` should take precedence of `alias` when both defined.

For instance:
```
$ cat .subgit.yml
repos:
  - url: git@github.com:Grokzen/pykwalify.git
    alias: pyk
  - url: git@github.com:Grokzen/pykwalify.git
    path: pyk/docs
  - url: git@github.com/Grokzen/pykwalify.git
    alias: pyk2
    path: pyk/tests

$ subgit pull pyk       # 'pyk' here is the alias and result in cloning to `./pyk`
$ subgit pull pyk/docs  # 'pyk/docs' here is the path and result in cloning to `./pyk/docs`
$ subgit pull pyk2      # 'pyk2' here is the alias, but path take precedence and result in cloning to `./pyk/tests`
```

In all cases, both `alias` and `path` entry is valid commands which results in action.

**Comment by Grokzen** [comment]
@rholmboe So i think i am a bit onboard on a few of the ideas, however i see some edge cases and corner cases that might be tricky.

So expanding the selector base to cover more cases i can get onboard with. However the UX for this will be both explicit & implicit where some things will be obvious like name/alias and some will be more hidden like the shortform repo name and the username+reponame combo that will just "happen". This is why i am still more in favor of only having name/alias explciitly and no other super magic targeting because it will just confuse and give way to many options. I rather have that you MUST set one name for each repo (i could agree to make it into a list with multiple entries) but to keep it only as explicit.

One cornercase tho is a config like this
```
$ cat .subgit.yml
repos:
  - url: git@gitlab.com:Grokzen/pykwalify.git
  - url: git@github.com:Grokzen/pykwalify.git
```

That would break down in your example with more implicit repo names because you would have two exact entries but one goes to another URL but using the same name scheme. This would mean that we would have to implement a bunch of logic to detect and prevent these things from happening, but also to really try to understand the URL part in all cases and we all know how fun regex is to match against URL:s (thinking of e-mail validation :)

This for me just reinforces the way simpler idea of "you set your own name for each repo" then you must call it `gitlab-pykwalify` and `github-pykwalify` but we as tools developers only have to check one set of names for duplicates super simple and not care about a hierarchy and order of possible names that should and should not be able to collide and override each other, even if that logic is way cooler :)

The change from `name` to `alias` is 50/50 for me. It is called a `git repo name` not a `git repo alias` so i will say that `name` should remain. But i do see that it might make more sense with `alias` given that it is a free text field

The feature that i will probably never believe would ever be used is to use the folder path as a repo selector. I would need to see a practical use-case from anyone before i would implement that really describing to me why they need it over any other solution simply using `cd <folder>` before you run your command kinda.

> This would result in cloning repository.git into ./repository and repo.git into ./repo

This part is already a standard within git tool itself. If i simply run `git clone git@github.com/Grokzen/pykwalify.git` it will automatically make a folder named `pykwalify` itself and clone it in there, we don't have todo or sort that out, it just happens automatically already.

**Comment by holmboe** [comment]
The case where:

```yaml
repos:
  - url: git@gitlab.com:Grokzen/pykwalify.git
  - url: git@github.com:Grokzen/pykwalify.git
```

...would result in a collision is easily handled. In the config file parsing logic, first derive `path` and `alias` from the `url` as @rholmboe proposed. Then loop over all the parsed entries and check if there are duplicate `path` or `alias` between them, if there are any let the user know that they need to change either in their config file. In this way it gets really explicit and no magic is needed.

If, and only if, we want to get fancy we could implement a suggestion based on smartness. The suggestion could identify that either the domain or the username varies between the two and use that to propose an alternative. I.e. `alias: github-pykwalify` vs `alias: gitlab-pykwalify`. This suggestion should not be smart behind the scenes, but only be used to suggest a path forward for the user which would of course add the change to their `.subgit.yml` themselves.
