### ISSUE TITLE
Change config format from dict to list of projects

### ISSUE THREAD

**Issue by Grokzen** [dynamist/subgit#49]
In order to better and much more simply facilitate the hierarchy and clone order and more where we might want to clone a second repo into some already cloned folder it would make much more sense and make it simpler to process and parse repos in order if the user would make the repo ordering.

Example of new format would be

```
repos:
  - name: books
    url: git@.../books.git
    revision:
      branch: master
  - name: windows
    url: git@.../windows.git
    revision:
      branch: master
```

Things that is affected by this is plenty, here is a few things that probably needs to be rewritten

- Parsing of config file when creating Core class
- The use and extraction of data within all existing commands, instead of iterating over key:value pairs it needs to be iterate over a list and extract the name from elsewhere instead.
- When init a new config file the default config needs to generate this correct syntax
- A possible

A possible good idea within these kinds of changes is to make a more dedicated and separate migration section within documentation that describes how a user migrates between different versions of the syntax. Another idea is to implement "versions" of the syntax that can be used to validate or check if this version of the cli really works with or supports a specific version of the config file or not. This however might be another ticket and probably should not be done in here right now
